name: Gitleaks Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Acci칩n oficial (sin par치metros)
      - uses: gitleaks/gitleaks-action@v2
        id: gitleaks
        continue-on-error: true          # no hace fallar el workflow

      # Subir el SARIF que la acci칩n genera autom치ticamente
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.gitleaks.outputs.sarif }}
