name: Semgrep Scan
on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        id: semgrep
        with:
          config: |
            p/secrets
            p/python
            p/flask
            p/security-audit

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.semgrep.outputs.sarif }}
