name: Semgrep Analysis

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Instalar Semgrep
      - name: Install Semgrep
        run: |
          curl -sL https://raw.githubusercontent.com/returntocorp/semgrep/develop/install.sh | sh

      # Ejecutar Semgrep y generar SARIF
      - name: Run Semgrep with SARIF output
        run: semgrep --config=./semgrep.yml --sarif --output=semgrep.sarif

      # Subir resultado SARIF a GitHub Code Scanning
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
